# Generated by Django 4.2.13 on 2026-07-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizedRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waypoints', models.JSONField(default=list, help_text='Ordered list of lat/lng waypoints')),
                ('total_distance_km', models.FloatField(blank=True, null=True)),
                ('estimated_duration_min', models.FloatField(blank=True, null=True)),
                ('traffic_conditions', models.CharField(blank=True, max_length=50)),
                ('weather_conditions', models.CharField(blank=True, max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
